### ISSUE TITLE
Game Boy Camera

### ISSUE THREAD

**Issue by chriskempson** [insidegadgets/GBCartRead#2]
Just wondering if this has been tested with a Game Boy Camera or not. Have tried a slow baud speed but I use I get the same header info back:

Game title... 0
MBC type... ROM ONLY
ROM size... 32KByte (no ROM banking)

I have tested with both the European and Japanese version of the Game Boy Camera and can successfully dump other ROMs but trying to dump this ROM results in a 0KB file.

**Comment by insidegadgets** [comment]
I haven't tested it myself (don't have a GB camera) but I've had 1-2 users advise me what needed to be changed to make the camera work which I believed to have been done in this version.

Here is one post/discussion on it: https://www.insidegadgets.com/2011/03/19/gbcartread-arduino-based-gameboy-cart-reader-%e2%80%93-part-1-read-the-rom/#comment-34814. Let me know if this post has helped and if I may have missed something in the code?

(I might buy one soon to test it myself)

**Comment by insidegadgets** [comment]
I received a Gameboy Camera (Model MGB-006 / GBD-EUR) and was able to dump the 1MB ROM and 128KB RAM. I read the pictures out of the save file using GBCameraDump as BGB just showed black pictures. 

Have you had any luck? One suggestion was to pull the CLK line low.
Do you have GB Cart Shield and if so which version?
