### ISSUE TITLE
Update to v1.8

### ISSUE THREAD

**Issue by grantland** [insidegadgets/GBCartRead#4]
I was having trouble getting GBCartRead to work with my board (v1.3 R2) with the contents of this repo (v1.6), until I noticed that you released v1.8 [here](https://www.insidegadgets.com/projects/gameboy-cart-shield/).

Would you be willing to update this repo? I think it could possible prevent others from running into this same issue. Thanks!

**Comment by insidegadgets** [comment]
Hi, Good idea, I've updated it and split off the older version to it's own folder. I was trying to keep the old version here because the code had some features that only works the GBCartShield so I wanted to keep the version up here simple. I'll keep this one up to date.

**Comment by grantland** [comment]
Thanks!

It would help in the future if you didn't "version" the contents of the repository, but instead relied on "releases" to upload or mark specific commits as specific releases. This way would also make it easier to see the changes from one version to the next :)
