### ISSUE TITLE
GBA Support

### ISSUE THREAD

**Issue by afska** [insidegadgets/GBCartRead#7]
I'm using a v1.5 DIY version of the reader and I'd like to know if it can be modified to support GBA games.

I understand that they use less voltage than regular GB carts, but besides that, are there other differences or it should work passing 3v instead of 5v in the positive pin?

**Comment by insidegadgets** [comment]
Hi, there is a difference in reading the rom and there is a lot of differences when reading saves and writing them back as there are different types. Take a look at our blog where we go into detail when we made GBxCart RW - https://www.insidegadgets.com/2016/12/25/gbxcartread-part-2-switching-to-ch340g-gba-rom-reading-sram-readwrite-and-determining-sizes/

**Comment by afska** [comment]
Great. I'll have a look at it.

Thanks!
